---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cerberus
  namespace: openshift-bcgov-cerberus
  labels:
    app: cerberus
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: cerberus
  name: cerberus
  namespace: openshift-bcgov-cerberus
spec:
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  output:
    to:
      kind: ImageStreamTag
      name: cerberus:latest
  source:
    secrets:
    - secret:
        name: platform-services-controlled-etc-pki-entitlement
      destinationDir: etc-pki-entitlement
    configMaps:
    - configMap:
        name: platform-services-controlled-rhsm-ca
      destinationDir: rhsm-ca
    - configMap:
        name: platform-services-controlled-rhsm-conf
      destinationDir: rhsm-conf
    git:
      ref: main
      uri: https://github.com/bcgov/platform-services-cerberus
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
