---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: cerberus
  name: cerberus-artifactory
  namespace: openshift-bcgov-cerberus
spec:
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  output:
    to:
      kind: DockerImage
      name: 'artifacts.developer.gov.bc.ca/plat-util-images/cerberus:test' #change to prod for production usage
    pushSecret:
      name: artifacts-platform-services
  source:
    contextDir: cerberus
    git:
      ref: main
      uri: https://github.com/bcgov/platform-services-sre
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
